name: CD

on:
  release:
    types: [published]

jobs:
  release:
    name: Release Workflow
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/release.yml

  docker-security:
    name: Docker Security Scan
    uses: ./.github/workflows/docker-security.yml