name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go:
    name: Go Workflow
    uses: ./.github/workflows/go.yml

  docker:
    name: Docker Workflow
    uses: ./.github/workflows/docker.yml