name: Docker Workflow

on:
  workflow_call:

jobs:

  dockerfile-lint:
    name: Lint Project Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Show Lint Results
        run: cat hadolint-results.sarif

  dockerfile-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs:
      - dockerfile-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.build
          push: false
          tags: myapp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max