name: Go Workflow

on:
  workflow_call:

jobs:
  go-lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Install dependencies
        run: go mod download

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger docs
        run: swag init -g cmd/main.go -o docs --parseDependency --parseInternal --useStructName

      - name: Run Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout 10m

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: go build -o bin/monitor-api cmd/main.g