name: Go Workflow

on:
  workflow_call:

jobs:
  go:
    name: Go CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Install dependencies
        run: make deps

      - name: Run Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout 10m

      - name: Install test dependencies
        run: make test-deps

      - name: Run unit tests
        run: make test-unit

      - name: Install documentation dependencies
        run: make docs-deps

      - name: Generate Swagger docs
        run: make docs